services:
  - type: web
    name: traccar
    env: docker
    plan: starter
    branch: main
    autoDeploy: true
    dockerfilePath: Dockerfile
    disk:
      name: traccar-data
      mountPath: /opt/traccar/data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 8082
